import { motion } from 'framer-motion'
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
import { Link } from 'react-router-dom'
import DataState from '../components/DataState'
import { useApi } from '../hooks/useApi'
import { inr, initials } from '../lib/api'

export default function ExecutiveDashboard() {
  const { data: ranking, loading, error } = useApi('/rankings/latest', { results: [], metrics: {} })
  const metrics = ranking?.metrics || {}
  const top = ranking?.results || []
  return <div className="pb-12">
    <DataState loading={loading} error={error}>
      <div className="flex items-center space-x-6 text-[13px] text-slate-500 mb-8 border-b border-slate-200/50 pb-4"><div className="flex items-center space-x-2"><i className="w-2 h-2 rounded-full bg-primary animate-pulse"/><strong className="text-slate-900 text-sm">{ranking?.processed_count?.toLocaleString()}</strong><span>Evaluated</span></div><i className="w-1 h-1 rounded-full bg-slate-300"/><div><strong className="text-slate-900 text-sm">{top.length}</strong> Ranked</div><i className="w-1 h-1 rounded-full bg-slate-300"/><div><strong className="text-success text-sm">{metrics.open_to_work_rate || 0}%</strong> Open to Work</div><div className="flex-1"/><span className="text-xs text-slate-400">Run #{ranking?.id} · {ranking?.duration_seconds}s · {ranking?.scope}</span></div>
      <div className="grid grid-cols-12 gap-6">
        <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="col-span-8 bg-white rounded-premium shadow-premium border border-slate-200/60 p-8 relative overflow-hidden"><div className="absolute top-0 right-0 w-96 h-96 bg-primary/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3"/><div className="relative flex justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Evidence-ranked shortlist</p><h2 className="text-3xl font-bold text-slate-900 mt-2">{metrics.average_score || 0}% <span className="text-lg text-slate-400 font-medium">average match</span></h2><p className="text-sm text-slate-500 mt-2">Top 100 candidates after integrity and behavioral adjustment.</p></div><Link to="/dashboard/candidates" className="h-fit px-4 py-2.5 bg-slate-900 text-white text-xs font-bold rounded-xl">Open shortlist</Link></div><div className="h-64 mt-8"><ResponsiveContainer width="100%" height="100%"><AreaChart data={top.slice(0, 30)}><defs><linearGradient id="dashScore" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2563EB" stopOpacity={0.25}/><stop offset="95%" stopColor="#2563EB" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9"/><XAxis dataKey="rank" axisLine={false} tickLine={false}/><YAxis domain={[0, 100]} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ borderRadius: 12, border: 'none' }}/><Area type="monotone" dataKey="score" stroke="#2563EB" strokeWidth={3} fill="url(#dashScore)"/></AreaChart></ResponsiveContainer></div><div className="grid grid-cols-4 gap-4 pt-5 border-t border-slate-100"><Mini label="Top-10 CPH" value={inr(metrics.average_top10_cph_inr, true)} /><Mini label="Projected savings" value={inr(metrics.top10_savings_inr, true)} tone="text-success" /><Mini label="Avg response" value={`${metrics.average_response_rate || 0}%`} /><Mini label="Integrity flags" value={metrics.integrity_flags_count || 0} tone="text-warning" /></div></motion.section>
        <div className="col-span-4 space-y-6">
          <section className="bg-white rounded-premium shadow-premium border border-slate-200/60 p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Recruiter ROI</p><h3 className="text-3xl font-bold text-success mt-1">{inr(metrics.top10_savings_inr, true)}</h3></div><span className="w-12 h-12 rounded-full bg-success/10 text-success flex items-center justify-center material-symbols-outlined">savings</span></div><p className="text-sm text-slate-500 mt-4">Projected savings across the top 10 against the ₹1.1L industry CPH benchmark.</p></section>
          <section className="bg-white rounded-premium shadow-premium border border-slate-200/60 p-6"><div className="flex justify-between items-center mb-4"><h3 className="font-bold text-slate-900">Top evidence matches</h3><Link to="/dashboard/candidates" className="text-xs font-bold text-primary">View all</Link></div><div className="space-y-4">{top.slice(0, 4).map((candidate) => <div key={candidate.candidate_id} className="flex items-center space-x-3"><div className="w-9 h-9 rounded-xl bg-primary/10 text-primary text-[10px] font-bold flex items-center justify-center">{initials(candidate.name)}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-900 truncate">{candidate.name}</p><p className="text-xs text-slate-400 truncate">{candidate.role} · {candidate.company}</p></div><span className="text-sm font-bold text-primary">{candidate.score.toFixed(1)}</span></div>)}</div></section>
        </div>
        <section className="col-span-12 bg-white rounded-premium shadow-premium border border-slate-200/60 p-6"><div className="flex justify-between items-center mb-5"><div><h3 className="font-bold text-slate-900">Decision funnel</h3><p className="text-xs text-slate-500">Auditable counts across the four-layer pipeline.</p></div><Link to="/dashboard/pipeline" className="text-xs font-bold text-primary">Inspect pipeline →</Link></div><div className="grid grid-cols-5 gap-4">{(metrics.pipeline || []).map((stage) => <div key={stage.stage} className="bg-slate-50 border border-slate-100 rounded-2xl p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{stage.stage}</p><p className="text-xl font-bold text-slate-900 mt-1">{stage.count.toLocaleString()}</p></div>)}</div></section>
      </div>
    </DataState>
  </div>
}
function Mini({ label, value, tone = 'text-slate-900' }) { return <div><p className="text-xs text-slate-400">{label}</p><p className={`font-bold mt-1 ${tone}`}>{value}</p></div> }
