import DataState from '../components/DataState'
import { useApi } from '../hooks/useApi'
import { initials } from '../lib/api'

export default function Settings() {
  const { data: user, loading, error } = useApi('/auth/me', {})
  const { data: ai } = useApi('/ai/status', {})
  return <div className="max-w-[1100px] w-full mx-auto pb-12"><div className="mb-8"><h1 className="text-3xl font-headline font-bold text-slate-900 mb-1">Settings</h1><p className="text-slate-500">Workspace identity and local intelligence configuration.</p></div><DataState loading={loading} error={error}>
    <div className="space-y-6"><section className="bg-white p-8 rounded-premium shadow-premium border border-slate-100"><div className="flex items-center justify-between mb-6 pb-6 border-b border-slate-100"><div><h3 className="text-xl font-bold text-slate-900">Workspace profile</h3><p className="text-sm text-slate-500 mt-1">Stored locally by the FastAPI SaaS shell.</p></div><span className={`text-xs font-bold px-3 py-1.5 rounded-lg ${user?.review_session ? 'bg-warning/10 text-warning' : 'bg-success/10 text-success'}`}>{user?.review_session ? 'Review session' : 'Authenticated'}</span></div><div className="flex items-center space-x-5"><div className="w-20 h-20 rounded-3xl bg-primary/10 text-primary flex items-center justify-center text-xl font-bold">{initials(`${user?.first_name || ''} ${user?.last_name || ''}`)}</div><div><h4 className="text-lg font-bold text-slate-900">{user?.first_name} {user?.last_name}</h4><p className="text-sm text-slate-500">{user?.email}</p><p className="text-sm font-medium text-primary mt-1">{user?.company}</p></div></div></section>
    <section className="bg-white p-8 rounded-premium shadow-premium border border-slate-100"><div className="flex justify-between items-start"><div><h3 className="text-xl font-bold text-slate-900">Local Ollama integration</h3><p className="text-sm text-slate-500 mt-1 max-w-2xl">Qwen is optional recruiter assistance. Competition ranking remains deterministic, CPU-only, network-free, and LLM-free.</p></div><span className={`text-xs font-bold px-3 py-1.5 rounded-lg ${ai?.available ? 'bg-success/10 text-success' : 'bg-slate-100 text-slate-500'}`}>{ai?.available ? 'Available' : ai?.enabled ? 'Unreachable' : 'Disabled'}</span></div><div className="mt-6 bg-slate-50 border border-slate-100 rounded-2xl p-4 grid grid-cols-3 gap-4"><div><p className="text-xs text-slate-400 uppercase font-bold">Endpoint</p><p className="text-sm font-mono text-slate-700 mt-1">127.0.0.1:11434</p></div><div><p className="text-xs text-slate-400 uppercase font-bold">Fast assistant</p><p className="text-sm font-mono text-slate-700 mt-1">{ai?.fast_model || 'not available'}</p></div><div><p className="text-xs text-slate-400 uppercase font-bold">Deep auditor</p><p className="text-sm font-mono text-slate-700 mt-1">{ai?.deep_model || 'not available'}</p></div></div><div className="grid grid-cols-2 gap-3 mt-4">{(ai?.profiles || []).map((profile) => <div key={profile.purpose} className="border border-slate-100 rounded-2xl p-4"><p className="text-xs font-bold text-slate-700">{profile.purpose}</p><p className="text-[11px] font-mono text-slate-500 mt-2">{profile.resolved || profile.configured}</p><span className={`inline-block mt-2 text-[10px] font-bold ${profile.available ? 'text-success' : 'text-warning'}`}>{profile.available ? 'READY' : 'MISSING'}</span></div>)}</div><p className="text-xs text-slate-500 mt-4">{ai?.message}</p></section>
    <section className="bg-white p-8 rounded-premium shadow-premium border border-slate-100"><div className="flex justify-between items-start"><div><h3 className="text-xl font-bold text-slate-900">Offline hybrid semantic retrieval</h3><p className="text-sm text-slate-500 mt-1 max-w-2xl">MiniLM embeddings complement explicit career and skill evidence. Candidate vectors are precomputed once; ranking uses local cosine similarity with no network.</p></div><span className={`text-xs font-bold px-3 py-1.5 rounded-lg ${ai?.semantic?.available ? 'bg-success/10 text-success' : 'bg-warning/10 text-warning'}`}>{ai?.semantic?.active ? 'Active' : ai?.semantic?.available ? 'Ready' : 'Artifact needed'}</span></div><div className="mt-6 grid grid-cols-3 gap-4 bg-slate-50 border border-slate-100 rounded-2xl p-4"><div><p className="text-xs uppercase font-bold text-slate-400">Embedding model</p><p className="text-xs font-mono text-slate-700 mt-2 break-words">{ai?.semantic?.model}</p></div><div><p className="text-xs uppercase font-bold text-slate-400">Candidate vectors</p><p className="text-lg font-bold text-slate-800 mt-1">{(ai?.semantic?.candidate_count || 0).toLocaleString()}</p></div><div><p className="text-xs uppercase font-bold text-slate-400">Network during ranking</p><p className="text-lg font-bold text-success mt-1">Never</p></div></div></section>
    </div>
  </DataState></div>
}
